name: Test

on:
  push:
    branches:
      - "**"
      - "!release-please--branches--main--*"

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          chatId: ${{ secrets.TELEGRAM_CHAT_ID }}
          messageThreadId: 3227
          text: "actions.telegram-notify 测试消息"
